name: game_2048
description: 2048 Game

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  audioplayers: ^5.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/